- name: Suscripcion de nodos administrados
  hosts: webservers
  gather_facts: False

  tasks:
    - name: Instalar subscription-manager
      ansible.builtin.yum:
        name: subscription-manager
        state: latest

    - name: Registrar como usuario con contraseña y auto-suscribirse a los contenidos disponibles
      redhat_subscription:
        state: present
        username: rutil.io
        password: M3ph1st0
        server_insecure: True
        auto_attach: True
        syspurpose:
          service_level_agreement: "Self-Support"

